cd ../ablation_analysis_results/
python choose_latent.py bprmf_analyze/no_sugar_regulation_scores.json bprmf_analyze/controller_no_sugar.json -x 100
cd ..
python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 1e-5 --sae_k 8 --sae_scale_size 16 --model_name BPRMF_SAE --emb_size 64 --lr 1e-3 --l2 1e-6 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 7 --use_mlp_controller 1 --tuning_dims no_sugar --eval_dims gluten_free,no_sugar,vegetarian,children_friendly,caffeine_free,low_price --loss_lambda 1 --model_path ../model/BPRMF_SAE/BPRMF_SAE__Grocery_and_Gourmet_Food__0__lr=0.001__l2=1e-06__emb_size=64__batch_size=256__sae_lr=1e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5
python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 1e-5 --sae_k 8 --sae_scale_size 16 --model_name BPRMF_SAE --emb_size 64 --lr 1e-3 --l2 1e-6 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 7 --use_mlp_controller 1 --tuning_dims no_sugar --eval_dims gluten_free,no_sugar,vegetarian,children_friendly,caffeine_free,low_price --loss_lambda 5 --model_path ../model/BPRMF_SAE/BPRMF_SAE__Grocery_and_Gourmet_Food__0__lr=0.001__l2=1e-06__emb_size=64__batch_size=256__sae_lr=1e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5
python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 1e-5 --sae_k 8 --sae_scale_size 16 --model_name BPRMF_SAE --emb_size 64 --lr 1e-3 --l2 1e-6 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 7 --use_mlp_controller 1 --tuning_dims no_sugar --eval_dims gluten_free,no_sugar,vegetarian,children_friendly,caffeine_free,low_price --loss_lambda 10 --model_path ../model/BPRMF_SAE/BPRMF_SAE__Grocery_and_Gourmet_Food__0__lr=0.001__l2=1e-06__emb_size=64__batch_size=256__sae_lr=1e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5
python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 1e-5 --sae_k 8 --sae_scale_size 16 --model_name BPRMF_SAE --emb_size 64 --lr 1e-3 --l2 1e-6 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 7 --use_mlp_controller 1 --tuning_dims no_sugar --eval_dims gluten_free,no_sugar,vegetarian,children_friendly,caffeine_free,low_price --loss_lambda 0.5 --model_path ../model/BPRMF_SAE/BPRMF_SAE__Grocery_and_Gourmet_Food__0__lr=0.001__l2=1e-06__emb_size=64__batch_size=256__sae_lr=1e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-5 --main_metric NDCG@5
python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 1e-5 --sae_k 8 --sae_scale_size 16 --model_name BPRMF_SAE --emb_size 64 --lr 1e-3 --l2 1e-6 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 7 --use_mlp_controller 1 --tuning_dims no_sugar --eval_dims gluten_free,no_sugar,vegetarian,children_friendly,caffeine_free,low_price --loss_lambda 50 --model_path ../model/BPRMF_SAE/BPRMF_SAE__Grocery_and_Gourmet_Food__0__lr=0.001__l2=1e-06__emb_size=64__batch_size=256__sae_lr=1e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-5 --main_metric NDCG@5
python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 1e-5 --sae_k 8 --sae_scale_size 16 --model_name BPRMF_SAE --emb_size 64 --lr 1e-3 --l2 1e-6 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 7 --use_mlp_controller 1 --tuning_dims no_sugar --eval_dims gluten_free,no_sugar,vegetarian,children_friendly,caffeine_free,low_price --loss_lambda 12 --model_path ../model/BPRMF_SAE/BPRMF_SAE__Grocery_and_Gourmet_Food__0__lr=0.001__l2=1e-06__emb_size=64__batch_size=256__sae_lr=1e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-5 --main_metric NDCG@5

# cd ablation_analysis_results/
# python choose_latent.py bprmf_analyze/no_sugar_regulation_scores.json bprmf_analyze/controller_no_sugar.json -x 50
# cd ..
# python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 1e-5 --sae_k 8 --sae_scale_size 16 --model_name BPRMF_SAE --emb_size 64 --lr 1e-3 --l2 1e-6 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 1 --use_mlp_controller 1 --tuning_dims no_sugar --eval_dims gluten_free,no_sugar,vegetarian,children_friendly,caffeine_free,low_price --loss_lambda 1 --model_path ../model/BPRMF_SAE/BPRMF_SAE__Grocery_and_Gourmet_Food__0__lr=0.001__l2=1e-06__emb_size=64__batch_size=256__sae_lr=1e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-5 --main_metric NDCG@5
# python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 1e-5 --sae_k 8 --sae_scale_size 16 --model_name BPRMF_SAE --emb_size 64 --lr 1e-3 --l2 1e-6 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 1 --use_mlp_controller 1 --tuning_dims no_sugar --eval_dims gluten_free,no_sugar,vegetarian,children_friendly,caffeine_free,low_price --loss_lambda 5 --model_path ../model/BPRMF_SAE/BPRMF_SAE__Grocery_and_Gourmet_Food__0__lr=0.001__l2=1e-06__emb_size=64__batch_size=256__sae_lr=1e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-5 --main_metric NDCG@5
# python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 1e-5 --sae_k 8 --sae_scale_size 16 --model_name BPRMF_SAE --emb_size 64 --lr 1e-3 --l2 1e-6 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 1 --use_mlp_controller 1 --tuning_dims no_sugar --eval_dims gluten_free,no_sugar,vegetarian,children_friendly,caffeine_free,low_price --loss_lambda 10 --model_path ../model/BPRMF_SAE/BPRMF_SAE__Grocery_and_Gourmet_Food__0__lr=0.001__l2=1e-06__emb_size=64__batch_size=256__sae_lr=1e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-5 --main_metric NDCG@5

# cd ablation_analysis_results/
# python choose_latent.py bprmf_analyze/no_sugar_regulation_scores.json bprmf_analyze/controller_no_sugar.json -x 100
# cd ..
# python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 1e-5 --sae_k 8 --sae_scale_size 16 --model_name BPRMF_SAE --emb_size 64 --lr 1e-3 --l2 1e-6 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 1 --use_mlp_controller 1 --tuning_dims no_sugar --eval_dims gluten_free,no_sugar,vegetarian,children_friendly,caffeine_free,low_price --loss_lambda 1 --model_path ../model/BPRMF_SAE/BPRMF_SAE__Grocery_and_Gourmet_Food__0__lr=0.001__l2=1e-06__emb_size=64__batch_size=256__sae_lr=1e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-5 --main_metric NDCG@5
# python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 1e-5 --sae_k 8 --sae_scale_size 16 --model_name BPRMF_SAE --emb_size 64 --lr 1e-3 --l2 1e-6 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 1 --use_mlp_controller 1 --tuning_dims no_sugar --eval_dims gluten_free,no_sugar,vegetarian,children_friendly,caffeine_free,low_price --loss_lambda 5 --model_path ../model/BPRMF_SAE/BPRMF_SAE__Grocery_and_Gourmet_Food__0__lr=0.001__l2=1e-06__emb_size=64__batch_size=256__sae_lr=1e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-5 --main_metric NDCG@5
# python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 1e-5 --sae_k 8 --sae_scale_size 16 --model_name BPRMF_SAE --emb_size 64 --lr 1e-3 --l2 1e-6 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 1 --use_mlp_controller 1 --tuning_dims no_sugar --eval_dims gluten_free,no_sugar,vegetarian,children_friendly,caffeine_free,low_price --loss_lambda 10 --model_path ../model/BPRMF_SAE/BPRMF_SAE__Grocery_and_Gourmet_Food__0__lr=0.001__l2=1e-06__emb_size=64__batch_size=256__sae_lr=1e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-5 --main_metric NDCG@5

# cd ablation_analysis_results/
# python choose_latent.py bprmf_analyze/no_sugar_regulation_scores.json bprmf_analyze/controller_no_sugar.json -x 15
# cd ..
# python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 1e-5 --sae_k 8 --sae_scale_size 16 --model_name BPRMF_SAE --emb_size 64 --lr 1e-3 --l2 1e-6 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 1 --use_mlp_controller 1 --tuning_dims no_sugar --eval_dims gluten_free,no_sugar,vegetarian,children_friendly,caffeine_free,low_price --loss_lambda 1 --model_path ../model/BPRMF_SAE/BPRMF_SAE__Grocery_and_Gourmet_Food__0__lr=0.001__l2=1e-06__emb_size=64__batch_size=256__sae_lr=1e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-5 --main_metric NDCG@5
# python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 1e-5 --sae_k 8 --sae_scale_size 16 --model_name BPRMF_SAE --emb_size 64 --lr 1e-3 --l2 1e-6 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 1 --use_mlp_controller 1 --tuning_dims no_sugar --eval_dims gluten_free,no_sugar,vegetarian,children_friendly,caffeine_free,low_price --loss_lambda 5 --model_path ../model/BPRMF_SAE/BPRMF_SAE__Grocery_and_Gourmet_Food__0__lr=0.001__l2=1e-06__emb_size=64__batch_size=256__sae_lr=1e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-5 --main_metric NDCG@5
# python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 1e-5 --sae_k 8 --sae_scale_size 16 --model_name BPRMF_SAE --emb_size 64 --lr 1e-3 --l2 1e-6 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 1 --use_mlp_controller 1 --tuning_dims no_sugar --eval_dims gluten_free,no_sugar,vegetarian,children_friendly,caffeine_free,low_price --loss_lambda 10 --model_path ../model/BPRMF_SAE/BPRMF_SAE__Grocery_and_Gourmet_Food__0__lr=0.001__l2=1e-06__emb_size=64__batch_size=256__sae_lr=1e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-5 --main_metric NDCG@5
