cd ../ablation_analysis_results/
python choose_latent.py bprmf_analyze/Drama_regulation_scores.json bprmf_analyze/controller_Drama.json -x 100
cd ..
python main_sae.py --epoch 50 --sae_batch_size 16 --sae_lr 1e-5 --sae_k 8 --sae_scale_size 16 --model_name BPRMF_SAE --emb_size 64 --lr 1e-3 --l2 1e-6 --dataset ML_1MTOPK_new --path ../data/ --test_all 1 --sae_train 1 --gpu 7 --use_mlp_controller 1 --tuning_dims Drama --eval_dims Drama,Comedy,Action,Thriller,Romance,Horror,Adventure,Sci-Fi,Crime --loss_lambda 0.2 --model_path ../model/BPRMF_SAE/BPRMF_SAE__ML_1MTOPK_new__0__lr=0.001__l2=1e-06__emb_size=64__batch_size=256__sae_lr=1e-05__sae_batch_size=16__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5
python main_sae.py --epoch 50 --sae_batch_size 16 --sae_lr 1e-5 --sae_k 8 --sae_scale_size 16 --model_name BPRMF_SAE --emb_size 64 --lr 1e-3 --l2 1e-6 --dataset ML_1MTOPK_new --path ../data/ --test_all 1 --sae_train 1 --gpu 7 --use_mlp_controller 1 --tuning_dims Drama --eval_dims Drama,Comedy,Action,Thriller,Romance,Horror,Adventure,Sci-Fi,Crime --loss_lambda 0.1 --model_path ../model/BPRMF_SAE/BPRMF_SAE__ML_1MTOPK_new__0__lr=0.001__l2=1e-06__emb_size=64__batch_size=256__sae_lr=1e-05__sae_batch_size=16__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5
python main_sae.py --epoch 50 --sae_batch_size 16 --sae_lr 1e-5 --sae_k 8 --sae_scale_size 16 --model_name BPRMF_SAE --emb_size 64 --lr 1e-3 --l2 1e-6 --dataset ML_1MTOPK_new --path ../data/ --test_all 1 --sae_train 1 --gpu 7 --use_mlp_controller 1 --tuning_dims Drama --eval_dims Drama,Comedy,Action,Thriller,Romance,Horror,Adventure,Sci-Fi,Crime --loss_lambda 0.05 --model_path ../model/BPRMF_SAE/BPRMF_SAE__ML_1MTOPK_new__0__lr=0.001__l2=1e-06__emb_size=64__batch_size=256__sae_lr=1e-05__sae_batch_size=16__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5

cd ablation_analysis_results/
python choose_latent.py bprmf_analyze/Drama_regulation_scores.json bprmf_analyze/controller_Drama.json -x 50
cd ..
python main_sae.py --epoch 50 --sae_batch_size 16 --sae_lr 1e-5 --sae_k 8 --sae_scale_size 16 --model_name BPRMF_SAE --emb_size 64 --lr 1e-3 --l2 1e-6 --dataset ML_1MTOPK_new --path ../data/ --test_all 1 --sae_train 1 --gpu 7 --use_mlp_controller 1 --tuning_dims Drama --eval_dims Drama,Comedy,Action,Thriller,Romance,Horror,Adventure,Sci-Fi,Crime --loss_lambda 0.2 --model_path ../model/BPRMF_SAE/BPRMF_SAE__ML_1MTOPK_new__0__lr=0.001__l2=1e-06__emb_size=64__batch_size=256__sae_lr=1e-05__sae_batch_size=16__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5
python main_sae.py --epoch 50 --sae_batch_size 16 --sae_lr 1e-5 --sae_k 8 --sae_scale_size 16 --model_name BPRMF_SAE --emb_size 64 --lr 1e-3 --l2 1e-6 --dataset ML_1MTOPK_new --path ../data/ --test_all 1 --sae_train 1 --gpu 7 --use_mlp_controller 1 --tuning_dims Drama --eval_dims Drama,Comedy,Action,Thriller,Romance,Horror,Adventure,Sci-Fi,Crime --loss_lambda 0.1 --model_path ../model/BPRMF_SAE/BPRMF_SAE__ML_1MTOPK_new__0__lr=0.001__l2=1e-06__emb_size=64__batch_size=256__sae_lr=1e-05__sae_batch_size=16__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5
python main_sae.py --epoch 50 --sae_batch_size 16 --sae_lr 1e-5 --sae_k 8 --sae_scale_size 16 --model_name BPRMF_SAE --emb_size 64 --lr 1e-3 --l2 1e-6 --dataset ML_1MTOPK_new --path ../data/ --test_all 1 --sae_train 1 --gpu 7 --use_mlp_controller 1 --tuning_dims Drama --eval_dims Drama,Comedy,Action,Thriller,Romance,Horror,Adventure,Sci-Fi,Crime --loss_lambda 0.05 --model_path ../model/BPRMF_SAE/BPRMF_SAE__ML_1MTOPK_new__0__lr=0.001__l2=1e-06__emb_size=64__batch_size=256__sae_lr=1e-05__sae_batch_size=16__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5

cd ablation_analysis_results/
python choose_latent.py bprmf_analyze/Drama_regulation_scores.json bprmf_analyze/controller_Drama.json -x 25
cd ..
python main_sae.py --epoch 50 --sae_batch_size 16 --sae_lr 1e-5 --sae_k 8 --sae_scale_size 16 --model_name BPRMF_SAE --emb_size 64 --lr 1e-3 --l2 1e-6 --dataset ML_1MTOPK_new --path ../data/ --test_all 1 --sae_train 1 --gpu 7 --use_mlp_controller 1 --tuning_dims Drama --eval_dims Drama,Comedy,Action,Thriller,Romance,Horror,Adventure,Sci-Fi,Crime --loss_lambda 0.2 --model_path ../model/BPRMF_SAE/BPRMF_SAE__ML_1MTOPK_new__0__lr=0.001__l2=1e-06__emb_size=64__batch_size=256__sae_lr=1e-05__sae_batch_size=16__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5
python main_sae.py --epoch 50 --sae_batch_size 16 --sae_lr 1e-5 --sae_k 8 --sae_scale_size 16 --model_name BPRMF_SAE --emb_size 64 --lr 1e-3 --l2 1e-6 --dataset ML_1MTOPK_new --path ../data/ --test_all 1 --sae_train 1 --gpu 7 --use_mlp_controller 1 --tuning_dims Drama --eval_dims Drama,Comedy,Action,Thriller,Romance,Horror,Adventure,Sci-Fi,Crime --loss_lambda 0.1 --model_path ../model/BPRMF_SAE/BPRMF_SAE__ML_1MTOPK_new__0__lr=0.001__l2=1e-06__emb_size=64__batch_size=256__sae_lr=1e-05__sae_batch_size=16__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5
python main_sae.py --epoch 50 --sae_batch_size 16 --sae_lr 1e-5 --sae_k 8 --sae_scale_size 16 --model_name BPRMF_SAE --emb_size 64 --lr 1e-3 --l2 1e-6 --dataset ML_1MTOPK_new --path ../data/ --test_all 1 --sae_train 1 --gpu 7 --use_mlp_controller 1 --tuning_dims Drama --eval_dims Drama,Comedy,Action,Thriller,Romance,Horror,Adventure,Sci-Fi,Crime --loss_lambda 0.05 --model_path ../model/BPRMF_SAE/BPRMF_SAE__ML_1MTOPK_new__0__lr=0.001__l2=1e-06__emb_size=64__batch_size=256__sae_lr=1e-05__sae_batch_size=16__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5

# cd ablation_analysis_results/
# python choose_latent.py bprmf_analyze/Drama_regulation_scores.json bprmf_analyze/controller_Drama.json -x 15
# cd ..
# python main_sae.py --epoch 50 --sae_batch_size 16 --sae_lr 1e-5 --sae_k 8 --sae_scale_size 16 --model_name BPRMF_SAE --emb_size 64 --lr 1e-3 --l2 1e-6 --dataset ML_1MTOPK_new --path ../data/ --test_all 1 --sae_train 1 --gpu 7 --use_mlp_controller 1 --tuning_dims Drama --eval_dims Drama,Comedy,Action,Thriller,Romance,Horror,Adventure,Sci-Fi,Crime --loss_lambda 0.2 --model_path ../model/BPRMF_SAE/BPRMF_SAE__ML_1MTOPK_new__0__lr=0.001__l2=1e-06__emb_size=64__batch_size=256__sae_lr=1e-05__sae_batch_size=16__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5
# python main_sae.py --epoch 50 --sae_batch_size 16 --sae_lr 1e-5 --sae_k 8 --sae_scale_size 16 --model_name BPRMF_SAE --emb_size 64 --lr 1e-3 --l2 1e-6 --dataset ML_1MTOPK_new --path ../data/ --test_all 1 --sae_train 1 --gpu 7 --use_mlp_controller 1 --tuning_dims Drama --eval_dims Drama,Comedy,Action,Thriller,Romance,Horror,Adventure,Sci-Fi,Crime --loss_lambda 0.1 --model_path ../model/BPRMF_SAE/BPRMF_SAE__ML_1MTOPK_new__0__lr=0.001__l2=1e-06__emb_size=64__batch_size=256__sae_lr=1e-05__sae_batch_size=16__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5
# python main_sae.py --epoch 50 --sae_batch_size 16 --sae_lr 1e-5 --sae_k 8 --sae_scale_size 16 --model_name BPRMF_SAE --emb_size 64 --lr 1e-3 --l2 1e-6 --dataset ML_1MTOPK_new --path ../data/ --test_all 1 --sae_train 1 --gpu 7 --use_mlp_controller 1 --tuning_dims Drama --eval_dims Drama,Comedy,Action,Thriller,Romance,Horror,Adventure,Sci-Fi,Crime --loss_lambda 0.05 --model_path ../model/BPRMF_SAE/BPRMF_SAE__ML_1MTOPK_new__0__lr=0.001__l2=1e-06__emb_size=64__batch_size=256__sae_lr=1e-05__sae_batch_size=16__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5
