cd ../ablation_analysis_results/
python choose_latent.py lightgcn_analyze/gluten_free_regulation_scores.json lightgcn_analyze/controller_gluten_free.json -x 100
cd ..
python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 5e-5 --sae_k 8 --sae_scale_size 16 --model_name LightGCN_SAE --emb_size 64 --lr 1e-3 --l2 1e-8 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 0 --use_mlp_controller 1 --tuning_dims gluten_free --eval_dims gluten_free,no_sugar,vegetarian,children_friendly,caffeine_free,low_price --loss_lambda 15 --model_path ../model/LightGCN_SAE/LightGCN_SAE__Grocery_and_Gourmet_Food__0__lr=0.001__l2=1e-08__emb_size=64__n_layers=3__batch_size=256__sae_lr=5e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5 
python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 5e-5 --sae_k 8 --sae_scale_size 16 --model_name LightGCN_SAE --emb_size 64 --lr 1e-3 --l2 1e-8 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 0 --use_mlp_controller 1 --tuning_dims gluten_free --eval_dims gluten_free,no_sugar,vegetarian,children_friendly,caffeine_free,low_price --loss_lambda 8 --model_path ../model/LightGCN_SAE/LightGCN_SAE__Grocery_and_Gourmet_Food__0__lr=0.001__l2=1e-08__emb_size=64__n_layers=3__batch_size=256__sae_lr=5e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5 
python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 5e-5 --sae_k 8 --sae_scale_size 16 --model_name LightGCN_SAE --emb_size 64 --lr 1e-3 --l2 1e-8 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 0 --use_mlp_controller 1 --tuning_dims gluten_free --eval_dims gluten_free,no_sugar,vegetarian,children_friendly,caffeine_free,low_price --loss_lambda 20 --model_path ../model/LightGCN_SAE/LightGCN_SAE__Grocery_and_Gourmet_Food__0__lr=0.001__l2=1e-08__emb_size=64__n_layers=3__batch_size=256__sae_lr=5e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5 

# cd ablation_analysis_results/
# python choose_latent.py lightgcn_analyze/gluten_free_regulation_scores.json lightgcn_analyze/controller_gluten_free.json -x 50
# cd ..
# python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 5e-5 --sae_k 8 --sae_scale_size 16 --model_name LightGCN_SAE --emb_size 64 --lr 1e-3 --l2 1e-8 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 6 --use_mlp_controller 1 --tuning_dims gluten_free --eval_dims gluten_free,no_sugar,vegetarian,children_friendly,caffeine_free,low_price --loss_lambda 1 --model_path ../model/LightGCN_SAE/LightGCN_SAE__Grocery_and_Gourmet_Food__0__lr=0.001__l2=1e-08__emb_size=64__n_layers=3__batch_size=256__sae_lr=5e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5 
# python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 5e-5 --sae_k 8 --sae_scale_size 16 --model_name LightGCN_SAE --emb_size 64 --lr 1e-3 --l2 1e-8 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 6 --use_mlp_controller 1 --tuning_dims gluten_free --eval_dims gluten_free,no_sugar,vegetarian,children_friendly,caffeine_free,low_price --loss_lambda 5 --model_path ../model/LightGCN_SAE/LightGCN_SAE__Grocery_and_Gourmet_Food__0__lr=0.001__l2=1e-08__emb_size=64__n_layers=3__batch_size=256__sae_lr=5e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5 
# python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 5e-5 --sae_k 8 --sae_scale_size 16 --model_name LightGCN_SAE --emb_size 64 --lr 1e-3 --l2 1e-8 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 6 --use_mlp_controller 1 --tuning_dims gluten_free --eval_dims gluten_free,no_sugar,vegetarian,children_friendly,caffeine_free,low_price --loss_lambda 10 --model_path ../model/LightGCN_SAE/LightGCN_SAE__Grocery_and_Gourmet_Food__0__lr=0.001__l2=1e-08__emb_size=64__n_layers=3__batch_size=256__sae_lr=5e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5 

# cd ablation_analysis_results/
# python choose_latent.py lightgcn_analyze/gluten_free_regulation_scores.json lightgcn_analyze/controller_gluten_free.json -x 100
# cd ..
# python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 5e-5 --sae_k 8 --sae_scale_size 16 --model_name LightGCN_SAE --emb_size 64 --lr 1e-3 --l2 1e-8 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 6 --use_mlp_controller 1 --tuning_dims gluten_free --eval_dims gluten_free,no_sugar,vegetarian,children_friendly,caffeine_free,low_price --loss_lambda 1 --model_path ../model/LightGCN_SAE/LightGCN_SAE__Grocery_and_Gourmet_Food__0__lr=0.001__l2=1e-08__emb_size=64__n_layers=3__batch_size=256__sae_lr=5e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5 
# python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 5e-5 --sae_k 8 --sae_scale_size 16 --model_name LightGCN_SAE --emb_size 64 --lr 1e-3 --l2 1e-8 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 6 --use_mlp_controller 1 --tuning_dims gluten_free --eval_dims gluten_free,no_sugar,vegetarian,children_friendly,caffeine_free,low_price --loss_lambda 5 --model_path ../model/LightGCN_SAE/LightGCN_SAE__Grocery_and_Gourmet_Food__0__lr=0.001__l2=1e-08__emb_size=64__n_layers=3__batch_size=256__sae_lr=5e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5 
# python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 5e-5 --sae_k 8 --sae_scale_size 16 --model_name LightGCN_SAE --emb_size 64 --lr 1e-3 --l2 1e-8 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 6 --use_mlp_controller 1 --tuning_dims gluten_free --eval_dims gluten_free,no_sugar,vegetarian,children_friendly,caffeine_free,low_price --loss_lambda 10 --model_path ../model/LightGCN_SAE/LightGCN_SAE__Grocery_and_Gourmet_Food__0__lr=0.001__l2=1e-08__emb_size=64__n_layers=3__batch_size=256__sae_lr=5e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5 

# cd ablation_analysis_results/
# python choose_latent.py lightgcn_analyze/gluten_free_regulation_scores.json lightgcn_analyze/controller_gluten_free.json -x 15
# cd ..
# python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 5e-5 --sae_k 8 --sae_scale_size 16 --model_name LightGCN_SAE --emb_size 64 --lr 1e-3 --l2 1e-8 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 6 --use_mlp_controller 1 --tuning_dims gluten_free --eval_dims gluten_free,no_sugar,vegetarian,children_friendly,caffeine_free,low_price --loss_lambda 1 --model_path ../model/LightGCN_SAE/LightGCN_SAE__Grocery_and_Gourmet_Food__0__lr=0.001__l2=1e-08__emb_size=64__n_layers=3__batch_size=256__sae_lr=5e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5 
# python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 5e-5 --sae_k 8 --sae_scale_size 16 --model_name LightGCN_SAE --emb_size 64 --lr 1e-3 --l2 1e-8 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 6 --use_mlp_controller 1 --tuning_dims gluten_free --eval_dims gluten_free,no_sugar,vegetarian,children_friendly,caffeine_free,low_price --loss_lambda 5 --model_path ../model/LightGCN_SAE/LightGCN_SAE__Grocery_and_Gourmet_Food__0__lr=0.001__l2=1e-08__emb_size=64__n_layers=3__batch_size=256__sae_lr=5e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5 
# python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 5e-5 --sae_k 8 --sae_scale_size 16 --model_name LightGCN_SAE --emb_size 64 --lr 1e-3 --l2 1e-8 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 6 --use_mlp_controller 1 --tuning_dims gluten_free --eval_dims gluten_free,no_sugar,vegetarian,children_friendly,caffeine_free,low_price --loss_lambda 10 --model_path ../model/LightGCN_SAE/LightGCN_SAE__Grocery_and_Gourmet_Food__0__lr=0.001__l2=1e-08__emb_size=64__n_layers=3__batch_size=256__sae_lr=5e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5 
