cd ../ablation_analysis_results/
python choose_latent.py caffeine_free_regulation_scores.json controller_caffeine_free.json -x 100
cd ..
python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 5e-05 --sae_k 8 --sae_scale_size 16 --model_name SASRec_SAE --emb_size 64 --num_layers 1 --num_heads 1 --lr 1e-4 --l2 1e-6 --history_max 20 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 0 --use_mlp_controller 1 --tuning_dims caffeine_free --eval_dims low_price,gluten_free,children_friendly,vegetarian,caffeine_free,no_sugar --loss_lambda 10.0 --model_path ../model/SASRec_SAE/SASRec_SAE__Grocery_and_Gourmet_Food__0__lr=0.0001__l2=1e-06__emb_size=64__num_layers=1__num_heads=1__sae_lr=5e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5
python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 5e-05 --sae_k 8 --sae_scale_size 16 --model_name SASRec_SAE --emb_size 64 --num_layers 1 --num_heads 1 --lr 1e-4 --l2 1e-6 --history_max 20 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 0 --use_mlp_controller 1 --tuning_dims caffeine_free --eval_dims low_price,gluten_free,children_friendly,vegetarian,caffeine_free,no_sugar --loss_lambda 5.0 --model_path ../model/SASRec_SAE/SASRec_SAE__Grocery_and_Gourmet_Food__0__lr=0.0001__l2=1e-06__emb_size=64__num_layers=1__num_heads=1__sae_lr=5e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5
python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 5e-05 --sae_k 8 --sae_scale_size 16 --model_name SASRec_SAE --emb_size 64 --num_layers 1 --num_heads 1 --lr 1e-4 --l2 1e-6 --history_max 20 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 0 --use_mlp_controller 1 --tuning_dims caffeine_free --eval_dims low_price,gluten_free,children_friendly,vegetarian,caffeine_free,no_sugar --loss_lambda 1.0 --model_path ../model/SASRec_SAE/SASRec_SAE__Grocery_and_Gourmet_Food__0__lr=0.0001__l2=1e-06__emb_size=64__num_layers=1__num_heads=1__sae_lr=5e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5

cd ablation_analysis_results/
python choose_latent.py caffeine_free_regulation_scores.json controller_caffeine_free.json -x 50
cd ..
python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 5e-05 --sae_k 8 --sae_scale_size 16 --model_name SASRec_SAE --emb_size 64 --num_layers 1 --num_heads 1 --lr 1e-4 --l2 1e-6 --history_max 20 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 0 --use_mlp_controller 1 --tuning_dims caffeine_free --eval_dims low_price,gluten_free,children_friendly,vegetarian,caffeine_free,no_sugar --loss_lambda 10.0 --model_path ../model/SASRec_SAE/SASRec_SAE__Grocery_and_Gourmet_Food__0__lr=0.0001__l2=1e-06__emb_size=64__num_layers=1__num_heads=1__sae_lr=5e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5
python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 5e-05 --sae_k 8 --sae_scale_size 16 --model_name SASRec_SAE --emb_size 64 --num_layers 1 --num_heads 1 --lr 1e-4 --l2 1e-6 --history_max 20 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 0 --use_mlp_controller 1 --tuning_dims caffeine_free --eval_dims low_price,gluten_free,children_friendly,vegetarian,caffeine_free,no_sugar --loss_lambda 5.0 --model_path ../model/SASRec_SAE/SASRec_SAE__Grocery_and_Gourmet_Food__0__lr=0.0001__l2=1e-06__emb_size=64__num_layers=1__num_heads=1__sae_lr=5e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5
python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 5e-05 --sae_k 8 --sae_scale_size 16 --model_name SASRec_SAE --emb_size 64 --num_layers 1 --num_heads 1 --lr 1e-4 --l2 1e-6 --history_max 20 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 0 --use_mlp_controller 1 --tuning_dims caffeine_free --eval_dims low_price,gluten_free,children_friendly,vegetarian,caffeine_free,no_sugar --loss_lambda 1.0 --model_path ../model/SASRec_SAE/SASRec_SAE__Grocery_and_Gourmet_Food__0__lr=0.0001__l2=1e-06__emb_size=64__num_layers=1__num_heads=1__sae_lr=5e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5

cd ablation_analysis_results/
python choose_latent.py caffeine_free_regulation_scores.json controller_caffeine_free.json -x 25
cd ..
python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 5e-05 --sae_k 8 --sae_scale_size 16 --model_name SASRec_SAE --emb_size 64 --num_layers 1 --num_heads 1 --lr 1e-4 --l2 1e-6 --history_max 20 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 0 --use_mlp_controller 1 --tuning_dims caffeine_free --eval_dims low_price,gluten_free,children_friendly,vegetarian,caffeine_free,no_sugar --loss_lambda 10.0 --model_path ../model/SASRec_SAE/SASRec_SAE__Grocery_and_Gourmet_Food__0__lr=0.0001__l2=1e-06__emb_size=64__num_layers=1__num_heads=1__sae_lr=5e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5
python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 5e-05 --sae_k 8 --sae_scale_size 16 --model_name SASRec_SAE --emb_size 64 --num_layers 1 --num_heads 1 --lr 1e-4 --l2 1e-6 --history_max 20 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 0 --use_mlp_controller 1 --tuning_dims caffeine_free --eval_dims low_price,gluten_free,children_friendly,vegetarian,caffeine_free,no_sugar --loss_lambda 5.0 --model_path ../model/SASRec_SAE/SASRec_SAE__Grocery_and_Gourmet_Food__0__lr=0.0001__l2=1e-06__emb_size=64__num_layers=1__num_heads=1__sae_lr=5e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5
python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 5e-05 --sae_k 8 --sae_scale_size 16 --model_name SASRec_SAE --emb_size 64 --num_layers 1 --num_heads 1 --lr 1e-4 --l2 1e-6 --history_max 20 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 0 --use_mlp_controller 1 --tuning_dims caffeine_free --eval_dims low_price,gluten_free,children_friendly,vegetarian,caffeine_free,no_sugar --loss_lambda 1.0 --model_path ../model/SASRec_SAE/SASRec_SAE__Grocery_and_Gourmet_Food__0__lr=0.0001__l2=1e-06__emb_size=64__num_layers=1__num_heads=1__sae_lr=5e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5

cd ablation_analysis_results/
python choose_latent.py caffeine_free_regulation_scores.json controller_caffeine_free.json -x 15
cd ..
python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 5e-05 --sae_k 8 --sae_scale_size 16 --model_name SASRec_SAE --emb_size 64 --num_layers 1 --num_heads 1 --lr 1e-4 --l2 1e-6 --history_max 20 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 0 --use_mlp_controller 1 --tuning_dims caffeine_free --eval_dims low_price,gluten_free,children_friendly,vegetarian,caffeine_free,no_sugar --loss_lambda 10.0 --model_path ../model/SASRec_SAE/SASRec_SAE__Grocery_and_Gourmet_Food__0__lr=0.0001__l2=1e-06__emb_size=64__num_layers=1__num_heads=1__sae_lr=5e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5
python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 5e-05 --sae_k 8 --sae_scale_size 16 --model_name SASRec_SAE --emb_size 64 --num_layers 1 --num_heads 1 --lr 1e-4 --l2 1e-6 --history_max 20 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 0 --use_mlp_controller 1 --tuning_dims caffeine_free --eval_dims low_price,gluten_free,children_friendly,vegetarian,caffeine_free,no_sugar --loss_lambda 5.0 --model_path ../model/SASRec_SAE/SASRec_SAE__Grocery_and_Gourmet_Food__0__lr=0.0001__l2=1e-06__emb_size=64__num_layers=1__num_heads=1__sae_lr=5e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5
python main_sae.py --epoch 50 --sae_batch_size 4 --sae_lr 5e-05 --sae_k 8 --sae_scale_size 16 --model_name SASRec_SAE --emb_size 64 --num_layers 1 --num_heads 1 --lr 1e-4 --l2 1e-6 --history_max 20 --dataset Grocery_and_Gourmet_Food --path ../data/ --test_all 1 --sae_train 1 --gpu 0 --use_mlp_controller 1 --tuning_dims caffeine_free --eval_dims low_price,gluten_free,children_friendly,vegetarian,caffeine_free,no_sugar --loss_lambda 1.0 --model_path ../model/SASRec_SAE/SASRec_SAE__Grocery_and_Gourmet_Food__0__lr=0.0001__l2=1e-06__emb_size=64__num_layers=1__num_heads=1__sae_lr=5e-05__sae_batch_size=4__sae_k=8__sae_scale_size=16.pt --mlp_lr 1e-4 --main_metric NDCG@5
